# Generated by Django 3.1.3 on 2021-11-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='naem',
            new_name='name',
        ),
    ]
