# Generated by Django 3.1.3 on 2021-11-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_order', '0002_auto_20211104_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
